version: "3.9"

services:
  # postgres setup
  postgres:
    build: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: "always"
    env_file:
      - "./postgres/app.env"
    volumes:
      - "./postgres/pg:/var/lib/postgresql/data"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "500M"
    networks:
      work-vnet:
        ipv4_address: 10.0.0.5
  go-user:
    build: ../
    container_name: go-user
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "126M"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      work-vnet:
        ipv4_address: 10.0.0.6
networks:
  work-vnet:
    name: infra-vnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
