service:
  name: 'go-user'
  httpPort: 8080
postgresRead:
  host: 'postgres'
  port: 5432
  database: 'user'
  username: 'postgres'
  password: 'postgresAdmin'
  timeZone: 'GMT'
  autoMigrate: true
  mode: 'read'
  enableLog: false
  maxConnection: 10
  # amount
  maxIdleConnection: 1
  # in minute
  maxIdleConnectionTtl: 5 
postgresWrite:
  host: 'postgres'
  port: 5432
  database: 'user'
  username: 'postgres'
  password: 'postgresAdmin'
  timeZone: 'GMT'
  autoMigrate: false
  mode: 'write'
  enableLog: false
  maxConnection: 10
  # amount
  maxIdleConnection: 1
  # in minute
  maxIdleConnectionTtl: 5 